### PR TITLE
Fix typography

### PR DESCRIPTION
**Pull request by whysetiawan**

### CODE REVIEW

**Comment by mateki0** [comment]
Hi @whysetiawan, can you describe what is fixed with this PR? Some screenshots and code snippets would be great. And also, can you read and follow our [Contribution Guide](https://github.com/TheWidlarzGroup/react-native-notificated/blob/master/CONTRIBUTING.md)?

I've did some tests with and without description/title weight props and it looks okay, but maybe I've missed something?
Screenshot 2023-06-20 at 09 59 34
Screenshot 2023-06-20 at 09 59 48

**Comment by whysetiawan** [comment]
I'm sorry i didn't read your guideline first. In my case, adding both weight and family of title/description props didn't work. My PR fixed this issue.

Screenshot 2023-06-21 at 17 12 41-copy

Screenshot 2023-06-21 at 17 21 16-copy

**Comment by mateki0** [comment]
> I'm sorry i didn't read your guideline first. In my case, adding both weight and family of title/description props didn't work. My PR fixed this issue.
> 
> Screenshot 2023-06-21 at 17 12 41-copy-2 Screenshot 2023-06-21 at 17 21 16-copy-2
> 
> here is my `package.json`
> 
> ```
> "react-native-notificated": "^0.1.0",
> "react-native-reanimated": "2.1.0",
> "react-native-gesture-handler": "^1.10.3",
> "react-native": "0.62.0",
> ```

Ok I've checked it once again today, and you're right. Thanks for catching it ! :) I don't know why it was working yesterday. Can you create a PR with proper branch name and PR title? This one won't pass our pipelines, and I don't want to create it by myself to not steal your contribution :)  @whysetiawan

**Comment by whysetiawan** [comment]
[#213](https://github.com/TheWidlarzGroup/react-native-notificated/pull/213)

**Pull request closed without merging**
